core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),  # Inclui as URLs do 'home'
    #path('login/', include('login.urls')),  # Inclui as URLs do 'login'
    path('portal_do_paciente/', include('portal_do_paciente.urls')),  # Inclui as URLs do 'portal_do_paciente'
    path('agendamentos/', include('agendamentos.urls'))

]

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('cadastro/', views.cadastro, name = 'cadastro'),
    path('login/', views.login_, name='login'),
    #path('adm/', views.view, name='adm'),
    #path('teste/', views.teste, name='teste'),
    ]

home/models.py
from django.db import models

# Create your models here.

medicos/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

# Create your models here.
class MedicoManager(BaseUserManager):
    """
    Gerenciador de usuários personalizados para o modelo Medico.
    """
    def create_user(self, cpf, password, **extra_fields):
        """
        Cria e salva um novo médico.
        """
        if not cpf:
            raise ValueError(_('O CPF é obrigatório'))
        if not extra_fields.get('crm'):
            raise ValueError(_('O CRM é obrigatório'))
        cpf = self.normalize_email(cpf)  # Use normalize_email para formatar o CPF (opcional)
        user = self.model(cpf=cpf, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, cpf, password, **extra_fields):
        """
        Cria e salva um novo superusuário médico.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superusuário precisa ter is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superusuário precisa ter is_superuser=True.'))

        return self.create_user(cpf, password, **extra_fields)

class Especialidade(models.Model):
    nome = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.nome


class Medico(AbstractBaseUser, PermissionsMixin):
    """
    Modelo de usuário Medico.
    """
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, unique=True, blank=True, null=True)  # Corrigido para EmailField e opcional
    data_de_nascimento = models.DateField(default=timezone.now)
    cpf = models.CharField(max_length=11, unique=True)  #Removido null=False, blank=True. CPF deve ser obrigatório.
    crm = models.CharField(max_length=20, unique=True)
    especialidade = models.ForeignKey(Especialidade, on_delete=models.SET_NULL, blank=True, null=True) # Relacionamento com Especialidade
    password = models.CharField(max_length=128)

    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'cpf'
    REQUIRED_FIELDS = ['email', 'crm', 'password']

    objects = MedicoManager()

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='medico_set',
        blank=True
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='medico_permissions_set',
        blank=True
    )

    def __str__(self):
        return self.nome

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib import messages
from pacientes.forms import PacienteForm
from pacientes.models import Paciente

def remover_formatacao_cpf(cpf:str = '123.456.789-10'):
  """
  Remove pontos e traços de um CPF formatado.

  Args:
      cpf: O CPF formatado (ex: '123.456.789-00').

  Returns:
      O CPF sem formatação (ex: '12345678900').
  """
  return cpf.replace('.', '').replace('-', '')



def home(request):
    #paciente = Paciente.objects.get(id=int(id))  # Obtenha o paciente

    context ={
     #   'paciente':paciente,#Chama-se com a chave, não o valor
    }
    return render(request, 'home.html')

def login_(request):
    
    """
    View para efetuar o login de um paciente.
    """
    if request.method == 'POST':
        cpf = request.POST.get('cpf')
        password = request.POST.get('password')

        print(password)
        print(cpf)
        # Autentica o usuário usando CPF (definido como username no modelo) e senha
        user = authenticate(username=cpf, password=str(password)) 
        print(user)

        if user is not None:
            login(request, user)
            messages.success(request, 'Login realizado com sucesso!')
            return redirect('portal_do_paciente', id=user.id)  # Redireciona para o portal do paciente
        else:
            messages.error(request, 'CPF ou senha inválidos!')
            return render(request, 'login.html')

    return render(request, 'login.html')

def cadastro(request):
    """
    View para cadastrar um novo paciente.
   """
    if request.method == 'POST':
        form = PacienteForm(request.POST)
        if form.is_valid():
            # Cria o novo paciente no banco de dados
            print(form)
            paciente = form.save(commit=False)  # Cria o objeto Paciente, mas não salva ainda
            
            # Define a senha usando set_password
            paciente.set_password(form.cleaned_data['password'])

            # Define a data de nascimento corretamente
            paciente.data_de_nascimento = form.cleaned_data['data_de_nascimento']
            paciente.nome = paciente.nome.title()
            # Salva o paciente no banco de dados
            paciente.is_staff = False
            paciente.is_superuser = False
            paciente.is_active = True
    
            paciente.save()

            # Faz o login do paciente recém-cadastrado
            login(request, paciente) 
            messages.success(request, 'Paciente cadastrado com sucesso!')

            return redirect('login')  # Redireciona para a página inicial após o cadastro
        else:
            # Imprime os erros do formulário para debugging
            print(form.errors)
            return render(request, 'cadastro.html', {'form': form})
    else:
        form = PacienteForm()
    return render(request, 'cadastro.html', {'form': form})
    

def teste(request):
    return render(request, 'teste.html')

def view(request):
    return render(request, 'administracao.html')

home/templates/administracao.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style_administracao.css' %}">
</head>
<body>

    <nav class="nav-bar">
        <a href="">Home</a>
        <a href="">Sobre</a>
        <a href="">Documentação</a>
    </nav>

    <div class="main-content">
        <div class="menu">
            <br>
            <div class="conteudo-menu">
                <a href="#documentacao">Pacientes</a>
                <a href="">Medicos</a>
            </div>
        </div>
        <div class="container">
            
            <div id="documentacao">
                <div  class="button-close"><p>x</p></div>
                
                <br>
                <p class="conteudo">Para alterar dados -> pacientes -> alterar -> pesquisar </p>
                
            </div>

        </div>
    </div>

</body>
</html>

home/templates/base.html
{% load static %}

<!DOCTYPE html>
<!--BASE DE TODOS OS TEMPLATES 18/10/2024-->
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/home/style_base.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body class="background-default">


    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <div class="container-fluid">
          {% if user.is_staff %}
          <a class="navbar-brand" href="{% url 'home_with_login' id_user=user.id %}">
            <img src="{% static 'images/authentication-29.png' %}" alt="Logo do Sistema de Gestão" width="50" height="50">
          </a>
          {% else %}
          <a class="navbar-brand" href="{% url 'home' %}">
            <img src="https://cdn-icons-png.flaticon.com/512/25/25694.png" alt="Ícone de Home" width="30" height="30">
          </a>
          {% endif %}
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">  
              
              {% if user.is_authenticated %} <!-- Verifica se o usuário está logado -->

              {% if not user.is_staff %} <!-- Para pacientes e outros usuários não staff -->
                  <a class="nav-link header_links" href="{% url 'home_with_login' id_user=user.id %}">Início</a>
                  <a class="nav-link header_links" href="{% url 'portal_do_paciente' id=user.id %}">Portal do paciente</a>
                  <a class="nav-link header_links" href="{% url 'logout' %}">Logout</a>
              {% else %} <!-- Para usuários staff -->
                  <a class="nav-link header_links" href="{% url 'home_with_login' id_user=user.id %}">Início</a>
                  <a class="nav-link header_links" href="{% url 'portal_do_paciente' id=user.id %}">Portal do paciente</a>
                  <a class="nav-link header_links" href="{% url 'gestao_de_pacientes' id=user.id %}">Paciente</a>
                  <a class="nav-link header_links" href="{% url 'gestao_de_medicos' id=user.id %}">Médicos</a>
                  <a class="nav-link header_links" href="{% url 'logout' %}">Logout</a>
              {% endif %}
          
          {% else %} <!-- Para visitantes não logados -->
              <a class="nav-link header_links" href="{% url 'home' %}">Início</a>
              <a class="nav-link header_links" href="{% url 'cadastro' %}">Cadastro</a>
              <a class="nav-link header_links" href="{% url 'login' %}">Login</a>
          {% endif %}

          </div>
        </div>
      </nav>
    </header>


    {% block content %}
    {% endblock %}

    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
      </ul>
    {% endif %}
    
      <div class="div-footer">
        <footer id="footer">
          <!--
          <p>© 2024 Direitos Reservados Softex</p>
          -->
          
        </footer>
      </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

home/templates/cadastro.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cadastro{% endblock %}

{% block content %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/home/style_cadastro.css' %}">

    
</head>
<body >
   

<div id="div-cadastro-voltar" class="container mt-3">
    <div id="div-voltar">
        <a class="link-any p_min" href="{% url 'home' %}	" >Voltar</a>
    </div>
    
</div>

    <div class="container mt-5" >
        <div class="text-center">
          <h2>Cadastro</h2>  
        </div>
        
        <div class="row justify-content-center">  <!-- Centraliza o formulário -->

            <div class="col-md-6" id="div-form-cadastro">  <!-- Define a largura máxima do formulário em telas médias -->
                <form method="POST" class="form-group">
                    {% csrf_token %}
                    {{ form.as_p }}
                     <button type="submit" class="btn btn-primary p_min">Cadastrar</button>
                </form>
                <br>
                <br>

                <br>
                            </div>
        </div>
        <script>
          function formatarCPF(cpf) {
  // Remove caracteres não numéricos
  cpf = cpf.replace(/[^0-9]/g, '');

  // Verifica se o CPF tem 11 dígitos
  if (cpf.length !== 11) {
    return cpf; // Retorna o CPF sem formatação se não tiver 11 dígitos
  }

  // Formata o CPF: xxx.xxx.xxx-xx
  return cpf.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/, '$1.$2.$3-$4');
}

// Exemplo de uso:
const inputCPF =document.querySelector("#id_cpf");

inputCPF.addEventListener('input', function() {
  this.value = formatarCPF(this.value);
});
        </script>
    </div>
    

{% endblock %}

home/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<title>{% block title %}Home{% endblock %}</title>

<<<<<<< HEAD
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style_home.css' %}">
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <img src="https://cdn-icons-png.flaticon.com/512/25/25694.png" alt="home" width="30" height="30">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">  
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cadastro' %}">Cadastre-se</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% comment %}
          {% endcomment %} 
        </ul>
      </div>
    </div>
  </nav>
</header>
  <div>
    <h1 >Sistema de agendamento e gerenciamento de consultas (SAGe)</h1>
    <div style="background-color: orange;" class="container">
=======
    
    <link rel="stylesheet" href="{% static 'css/home/style_home.css' %}">
  <div class="container">
    <h1 ></h1>
    
    <div class="container">
>>>>>>> 88ec43849ce0555310307bf3fa9f322d2c66caf1

      <h2 style="color: red;">Versão demo ...</h2>

      <p style="color: red"> Os dados são fictícios !  </p>

      {% comment  %}
      <p>Com este sistema, você tem a praticidade de agendar suas consultas de forma rápida e fácil, diretamente do seu computador ou dispositivo móvel.</p>
 
      <h2>Aproveite os benefícios:</h2>
  
      <ul>
          <li>Agendamento 24 horas por dia, 7 dias por semana: Acesse o sistema a qualquer momento e agende sua consulta no horário que melhor lhe convém.</li>
          <li>Visualização de horários disponíveis: Encontre a data e hora ideal para você, sem necessidade de telefonemas ou filas.</li>
          <li>Confirmação rápida e segura: Receba a confirmação do seu agendamento por email, garantindo que sua consulta está agendada.</li>
          <li>Gerenciamento completo: Acesse seus agendamentos, cancele ou altere suas consultas com total autonomia.</li>
      </ul>
  
      <a class="div-link" href="{% url 'cadastro' %}">Cadastre-se</a>
    </div>
  </div>
  {% endcomment %}

  {% endblock %}

home/templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Login{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/home/style_login.css' %}">
<script src="{% static 'js/js_login.js' %}" defer></script>
  <main class="main">
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}

    
    <div class="container mt-5">
      <div class="row justify-content-center">
          <div class="col-md-6">
              <div class="card p-4">
                  <h2 class="h1_max text-center mb-4">Login</h2>
                  <form method="post">
                      {% csrf_token %}

                      <div class="form-group">
                          <label class="h1_min" for="cpf">CPF</label>
                          <input type="text" class="form-control p_max" id="cpf" name="cpf" placeholder="Digite seu CPF" required>
                      </div>

                      <div class="form-group">
                          <label class="h1_min" for="password">Senha</label>
                          <input type="password" class="form-control p_max" id="password" name="password" placeholder="Digite sua senha" required>
                      </div>
                  
                      <button type="submit" class="link-any btn-primary btn-block p_max text-center">Entrar</button>
                  </form>
              </div>
          </div>
      </div>
  </div>
  </main>
{% endblock %}

home/templates/sucesso.html
deu certo

home/templates/teste.html
{% extends 'base.html' %}

{% block title %}Página Específica{% endblock %}

{% block content %}
  <div class="container">
    <h1>Título da Página Específica</h1>
    <p>Este é um texto de exemplo para a página específica.</p>
  </div>

  
{% endblock %}